#!/bin/bash
# Created by Phillip Wilson <pswilso2017@github>

#qemu-img create -f qcow2 -b /var/lib/libvirt/images/rhcos-qemu.s390x.qcow2 /var/lib/libvirt/images/bootstrap.qcow2 70G
#qemu-img create -f qcow2 -b /var/lib/libvirt/images/rhcos-qemu.s390x.qcow2 /var/lib/libvirt/images/control-1.qcow2 70G
#qemu-img create -f qcow2 -b /var/lib/libvirt/images/rhcos-qemu.s390x.qcow2 /var/lib/libvirt/images/control-2.qcow2 70G
#qemu-img create -f qcow2 -b /var/lib/libvirt/images/rhcos-qemu.s390x.qcow2 /var/lib/libvirt/images/control-3.qcow2 70G
#qemu-img create -f qcow2 -b /var/lib/libvirt/images/rhcos-qemu.s390x.qcow2 /var/lib/libvirt/images/worker-1.qcow2 70G
#qemu-img create -f qcow2 -b /var/lib/libvirt/images/rhcos-qemu.s390x.qcow2 /var/lib/libvirt/images/worker-2.qcow2 70G

#virt-install --boot kernel=rhcos-kernel,initrd=rhcos-initramfs.img,kernel_args='rd.neednet=1 coreos.inst.install_dev=/dev/vda coreos.live.rootfs_url=http://<bastion-IP><bastion-IP>:8080/bin/rhcos-rootfs.img coreos.inst.ignition_url=http://<bastion-IP>:8080/ignition/bootstrap.ign ip=<bootstrap-IP>::<gateway-IP>:<subnet-mask>:::none nameserver=<bastion-IP>' --connect qemu:///system --name bootstrap --memory 16384 --vcpus 4 --disk /var/lib/libvirt/images/bootstrap.qcow2 --accelerate --import --network network=macvtap-net --qemu-commandline="-drive if=none,id=ignition,format=raw,file=/var/www/html/ignition/bootstrap.ign,readonly=on -device virtio-blk,serial=ignition,drive=ignition" --noautoconsole

#virt-install --boot kernel=rhcos-kernel,initrd=rhcos-initramfs.img,kernel_args='rd.neednet=1 coreos.inst.install_dev=/dev/vda coreos.live.rootfs_url=http://<bastion-IP>:8080/bin/rhcos-rootfs.img coreos.inst.ignition_url=http://<bastion-IP>:8080/ignition/master.ign ip=<control-node1-ip>::<gateway-IP>:<subnet-mask>:::none nameserver=<bastion-IP>' --connect qemu:///system --name control-1 --memory 16384 --vcpus 4 --disk /var/lib/libvirt/images/control-1.qcow2 --accelerate --import --network network=macvtap-net --qemu-commandline="-drive if=none,id=ignition,format=raw,file=/var/www/html/ignition/master.ign,readonly=on -device virtio-blk,serial=ignition,drive=ignition" --noautoconsole

#virt-install --boot kernel=rhcos-kernel,initrd=rhcos-initramfs.img,kernel_args='rd.neednet=1 coreos.inst.install_dev=/dev/vda coreos.live.rootfs_url=http://<bastion-IP>:8080/bin/rhcos-rootfs.img coreos.inst.ignition_url=http://<bastion-IP>:8080/ignition/master.ign ip=<control-node2-ip>::<gateway-IP>:<subnet-mask>:::none nameserver=<bastion-IP>' --connect qemu:///system --name control-2 --memory 16384 --vcpus 4 --disk /var/lib/libvirt/images/control-2.qcow2 --accelerate --import --network network=macvtap-net --qemu-commandline="-drive if=none,id=ignition,format=raw,file=/var/www/html/ignition/master.ign,readonly=on -device virtio-blk,serial=ignition,drive=ignition" --noautoconsole

#virt-install --boot kernel=rhcos-kernel,initrd=rhcos-initramfs.img,kernel_args='rd.neednet=1 coreos.inst.install_dev=/dev/vda coreos.live.rootfs_url=http://<bastion-IP>:8080/bin/rhcos-rootfs.img coreos.inst.ignition_url=http://<bastion-IP>:8080/ignition/master.ign ip=<control-node2-ip>::<gateway-IP>:<subnet-mask>:::none nameserver=<bastion-IP>' --connect qemu:///system --name control-3 --memory 16384 --vcpus 4 --disk /var/lib/libvirt/images/control-3.qcow2 --accelerate --import --network network=macvtap-net --qemu-commandline="-drive if=none,id=ignition,format=raw,file=/var/www/html/ignition/master.ign,readonly=on -device virtio-blk,serial=ignition,drive=ignition" --noautoconsole

#virt-install --boot kernel=rhcos-kernel,initrd=rhcos-initramfs.img,kernel_args='rd.neednet=1 coreos.inst.install_dev=/dev/vda coreos.live.rootfs_url=http://<bastion-IP>:8080/bin/rhcos-rootfs.img coreos.inst.ignition_url=http://<bastion-IP>:8080/ignition/worker.ign ip=<worker-node1-ip>::<gateway-IP>:<subnet-mask>:::none nameserver=<bastion-IP>' --connect qemu:///system --name worker-1 --memory 16384 --vcpus 4 --disk /var/lib/libvirt/images/worker-1.qcow2 --accelerate --import --network network=macvtap-net --qemu-commandline="-drive if=none,id=ignition,format=raw,file=/var/www/html/ignition/worker.ign,readonly=on -device virtio-blk,serial=ignition,drive=ignition" --noautoconsole

#virt-install --boot kernel=rhcos-kernel,initrd=rhcos-initramfs.img,kernel_args='rd.neednet=1 coreos.inst.install_dev=/dev/vda coreos.live.rootfs_url=http://<bastion-IP>:8080/bin/rhcos-rootfs.img coreos.inst.ignition_url=http://<bastion-IP>:8080/ignition/worker.ign ip=<worker-node2-ip>::<gateway-IP>:<subnet-mask>:::none nameserver=<bastion-IP>' --connect qemu:///system --name worker-2 --memory 16384 --vcpus 4 --disk /var/lib/libvirt/images/worker-2.qcow2 --accelerate --import --network network=macvtap-net --qemu-commandline="-drive if=none,id=ignition,format=raw,file=/var/www/html/ignition/worker.ign,readonly=on -device virtio-blk,serial=ignition,drive=ignition" --noautoconsole
